### ISSUE TITLE
Is there any plan to support ESP32-C3 RISC-V

### ISSUE THREAD

**Issue by yoozaa80** [ccrause/fpc-esp-freertos#8]
Is there any plan to support ESP32-C3 RISC-V ?
ESP8266 and ESP32-S run very smoothly! Thanks

**Comment by ccrause** [comment]
I would in principle like to extend support to other esp-idf controllers such as the ESP32-C3.  Unfortunately I have very little time at the moment since other projects are keeping me busy.

**Comment by yoozaa80** [comment]
Thank you for your hard work! Thank you. Let me try again
